_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 12
                - 45
                - 55
            "2":
                - 12
                - 45
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.17
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
ACTIVATION:
    value: relu
ALG_NAME:
    value: PPO
ANNEAL_LR:
    value: true
CHECKPOINT_DIR:
    value: ./checkpoints
CHECKPOINT_FREQ:
    value: 10
CLIP_EPS:
    value: 0.2
ENT_COEF:
    value: 0.01
ENTITY:
    value: ""
ENV_NAME:
    value: JaxSeaquest
GAE_LAMBDA:
    value: 0.95
GAMMA:
    value: 0.99
LR:
    value: 0.00025
MAX_GRAD_NORM:
    value: 0.5
NUM_ENVS:
    value: 128
NUM_MINIBATCHES:
    value: 4
NUM_STEPS:
    value: 128
PROJECT:
    value: ""
TOTAL_TIMESTEPS:
    value: 1e+09
UPDATE_EPOCHS:
    value: 4
VF_COEF:
    value: 0.5
WANDB_MODE:
    value: online
