_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 12
                - 45
                - 55
            "2":
                - 12
                - 45
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.17
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
ACTIVATION:
    value: relu
ALG_NAME:
    value: ModelBasedPPO
ANNEAL_LR:
    value: true
CHECKPOINT_DIR:
    value: ./checkpoints
CLIP_EPS:
    value: 0.2
ENT_COEF:
    value: 0.01
ENTITY:
    value: ""
ENV_NAME:
    value: JaxSeaquest
FRAME_STACK_SIZE:
    value: 1
GAE_LAMBDA:
    value: 0.95
GAMMA:
    value: 0.99
LR:
    value: 0.00025
MAX_GRAD_NORM:
    value: 0.5
MODEL_ARCHITECTURE:
    value: model_architectures.V2_LSTM
NUM_ENVS:
    value: 64
NUM_ITERATIONS:
    value: 5
NUM_MINIBATCHES:
    value: 4
NUM_STEPS:
    value: 128
PROJECT:
    value: ""
REAL_ENV_EPISODES:
    value: 20
REAL_ENV_MAX_STEPS:
    value: 1000
TOTAL_TIMESTEPS:
    value: 1e+06
UPDATE_EPOCHS:
    value: 4
VF_COEF:
    value: 0.5
WANDB_MODE:
    value: online
WORLD_MODEL_EPOCHS:
    value: 50
